# Generated by Django 3.0.1 on 2020-09-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos_galeroa',
            new_name='Videos_galeria',
        ),
    ]
