# Generated by Django 3.0.1 on 2020-08-22 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id_tema', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(1, 'Revisado'), (2, 'Pendiente')])),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo del tema')),
                ('descripcion', models.TextField(blank=True, max_length='900', verbose_name='Descripcion del tema')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Videos_Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='', verbose_name='Video del tema')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes_Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Imagen del tema')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Audio_Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, upload_to='', verbose_name='Audio del tema')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Tema')),
            ],
        ),
    ]
