# Generated by Django 3.0.1 on 2020-09-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20200911_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
