# Generated by Django 3.0.1 on 2020-08-22 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_audio_tema_imagenes_tema_tema_videos_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Tema',
            fields=[
                ('id_categoria_tema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(blank=True, max_length=200, verbose_name='Nombre de la categoria')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Tema')),
            ],
        ),
    ]
