# Generated by Django 3.0.1 on 2020-09-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20200822_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos_galeroa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, upload_to='video/', verbose_name='Video del tema')),
                ('id_galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Galeria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes_galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/', verbose_name='Imagen del tema')),
                ('id_galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Galeria')),
            ],
        ),
    ]
