# Generated by Django 3.1 on 2020-09-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_galeria_imagenes_galeria_videos_galeroa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos_galeroa',
            new_name='Videos_galeria',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
